---

    - name: Install pip
      apt:
        name: python-pip 
        state: present

    - name: install docker-py
      pip: 
        name: docker-py

    - name: Running the container
      docker:
        name: "{{ name }}"
        image: "{{ image }}:{{ tag }}"
        command: "{{ command }}"
        ports:
          - "{{ ports }}"
        detach: true
        state: running
