---

    - name: "create directory path to store the configuration files"
      file:
        path: "/opt/{{ docker_run_appname }}"
        state: directory
        mode: 0755
      
    - name: Touch the configuration file 
      file:
        path: /opt/{{ docker_run_appname }}/.env
        state: touch
        mode: u=rw,g=r,o=r
        

    - name: Set environment variables
      lineinfile:
        path: /opt/{{ docker_run_appname }}/.env
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      with_dict: "{{ docker_run_env_variables }}"


    - name: Running the container
      docker_container:
        name: "{{ docker_run_appname }}"
        image: "{{ docker_run_image }}:{{ docker_run_tag }}"
        env_file: /opt/{{ docker_run_appname }}/.env
        command: "{{ docker_run_command }}"
        ports: "{{ docker_run_ports }}"
        volumes: /data:"{{ docker_run_volume }}"
        detach: True
        state: started
